# Generated by Django 3.2 on 2021-06-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ongoingridesnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikenum', models.TextField()),
                ('ridername', models.CharField(max_length=150)),
                ('ridernum', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('currentlocation', models.TextField()),
            ],
        ),
    ]
