# Generated by Django 3.2 on 2021-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alertsandnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_alert', models.TextField()),
                ('dateandtime', models.DateTimeField()),
            ],
        ),
    ]
