# Generated by Django 3.2 on 2021-06-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alertsandnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logodetails', models.TextField()),
                ('dateandthetime', models.DateTimeField()),
                ('details', models.TextField()),
                ('logo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
