# Generated by Django 3.2 on 2021-06-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_auto_20210606_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='logos',
            name='bikelogo',
            field=models.ImageField(default=0, upload_to='imgs'),
            preserve_default=False,
        ),
    ]
