# Generated by Django 3.2 on 2021-06-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_logos_bikelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='allorderslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField()),
                ('date_of_order', models.DateTimeField()),
                ('bike_num', models.TextField()),
                ('rider_name', models.CharField(max_length=150)),
                ('id_proof', models.TextField()),
                ('total_kms', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('bike_collector', models.TextField()),
                ('booking_charges', models.IntegerField()),
            ],
        ),
    ]
