# Generated by Django 3.2 on 2021-06-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_allorderslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allorderslist',
            name='payment',
            field=models.TextField(),
        ),
    ]
